trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.8.1'
  displayName: 'Use Node.js 12.8.1'

- script: |
    npm ci
  displayName: 'Install dependencies'

- script: |
    npm run lint:client
    npm run compile:client
  displayName: 'Compile client'

- script: |
    npm run lint:server
    npm run compile:server
  displayName: 'Compile server'